export const    ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS';
export const    ADD_PRODUCT_FAILURE='ADD_PRODUCT_FAILURE';
export const    PRODUCT_FETCH_SUCCESS='PRODUCT_FETCH_SUCCESS';
export const    PRODUCT_FETCH_FAILURE='PRODUCT_FETCH_FAILURE';